info:
  description: ''
  title: ''
  version: ''
openapi: 3.0.0
paths:
  /swagger-docs/:
    get:
      operationId: swagger-docs_list
      tags:
      - swagger-docs
servers:
- url: ''
